--44)
SELECT	DEPT_NAME
FROM	LGDEPARTMENT

--45)
SELECT	PROD_SKU, PROD_DESCRIPT, PROD_TYPE, PROD_BASE, PROD_CATEGORY, PROD_PRICE
FROM	LGPRODUCT
WHERE	PROD_BASE = 'Water' AND PROD_CATEGORY = 'Sealer'

--46)
SELECT	EMP_FNAME, EMP_LNAME, EMP_EMAIL, EMP_HIREDATE
FROM	LGEMPLOYEE
WHERE	EMP_HIREDATE >= '2003-1-1' AND EMP_HIREDATE <= '2012-12-31'
ORDER BY EMP_LNAME, EMP_FNAME

--47)
SELECT	EMP_FNAME, EMP_LNAME, EMP_PHONE, EMP_TITLE, DEPT_NUM
FROM	LGEMPLOYEE
WHERE	DEPT_NUM = 300 OR EMP_TITLE = 'CLERK I'
ORDER BY EMP_LNAME, EMP_FNAME

--48)******
SELECT	LGEMPLOYEE.EMP_NUM, EMP_LNAME, EMP_FNAME, SAL_FROM, SAL_END, SAL_AMOUNT
FROM	LGEMPLOYEE, LGSALARY_HISTORY
WHERE	LGEMPLOYEE.EMP_NUM = 83731 OR
		LGEMPLOYEE.EMP_NUM = 83745 OR
		LGEMPLOYEE.EMP_NUM = 84039
ORDER BY LGEMPLOYEE.EMP_NUM, SAL_FROM 

--49)********
SELECT	DISTINCT CUST_FNAME, CUST_LNAME, CUST_STREET, CUST_CITY, CUST_STATE, CUST_ZIP
FROM	LGCUSTOMER, LGINVOICE, LGBRAND, LGPRODUCT
WHERE	BRAND_NAME = 'FORESTERS BEST' AND
		(INV_DATE > '2015-07-15' AND INV_DATE < '2015-07-31') AND
		PROD_CATEGORY = 'Top Coat'
ORDER BY CUST_STATE, CUST_LNAME, CUST_FNAME

--50)
SELECT	LGEMPLOYEE.EMP_NUM, EMP_LNAME, EMP_EMAIL, EMP_TITLE, DEPT_NAME
FROM	LGEMPLOYEE, LGDEPARTMENT
WHERE	EMP_TITLE LIKE '%ASSOCIATE'
ORDER BY DEPT_NAME, EMP_TITLE

--51)
SELECT	BRAND_NAME, COUNT(PROD_DESCRIPT)
FROM	LGBRAND, LGPRODUCT
WHERE	LGBRAND.BRAND_ID = LGPRODUCT.BRAND_ID
GROUP BY BRAND_NAME

--52)
SELECT	PROD_CATEGORY, COUNT(PROD_DESCRIPT) AS [NUMPRODUCTS]
FROM	LGPRODUCT
WHERE	PROD_BASE = 'Water'
GROUP BY PROD_CATEGORY

--53)
SELECT	PROD_BASE, PROD_TYPE, COUNT(PROD_DESCRIPT) AS [NUMPRODUCTS]
FROM	LGPRODUCT
GROUP BY PROD_BASE, PROD_TYPE

--54)
SELECT	BRAND_ID, SUM(PROD_QOH) AS [TOTALINVENTORY]
FROM	LGPRODUCT
GROUP BY BRAND_ID 
ORDER BY BRAND_ID DESC

--55)
SELECT  LGBRAND.BRAND_ID, BRAND_NAME, AVG(PROD_PRICE)
FROM	LGBRAND, LGPRODUCT
WHERE	LGBRAND.BRAND_ID = LGPRODUCT.BRAND_ID
GROUP BY LGBRAND.BRAND_ID, BRAND_NAME
ORDER BY BRAND_NAME

--56)
SELECT	DEPT_NUM, MAX(EMP_HIREDATE) AS [MOSTRECENT]
FROM	LGEMPLOYEE
GROUP BY DEPT_NUM

--57)
SELECT	LGEMPLOYEE.EMP_NUM, EMP_FNAME, EMP_LNAME, MAX(SAL_AMOUNT)
FROM	LGEMPLOYEE, LGSALARY_HISTORY
WHERE	DEPT_NUM = 200
		AND LGEMPLOYEE.EMP_NUM = LGSALARY_HISTORY.EMP_NUM
GROUP BY LGEMPLOYEE.EMP_NUM, EMP_FNAME, EMP_LNAME
ORDER BY MAX(SAL_AMOUNT) DESC

--58)
SELECT	LGCUSTOMER.CUST_CODE, CUST_FNAME, CUST_LNAME, SUM(INV_TOTAL) AS [INVOICETOTALS]
FROM	LGCUSTOMER, LGINVOICE
WHERE	LGCUSTOMER.CUST_CODE = LGINVOICE.CUST_CODE
		AND (SELECT SUM(INV_TOTAL) FROM LGINVOICE) > 1500
GROUP BY LGCUSTOMER.CUST_CODE, CUST_FNAME, CUST_LNAME
ORDER BY SUM(INV_TOTAL) DESC

--59)
SELECT LGDEPARTMENT.DEPT_NUM, DEPT_NAME, DEPT_PHONE, LGDEPARTMENT.EMP_NUM, EMP_LNAME
FROM	LGEMPLOYEE, LGDEPARTMENT
WHERE	LGDEPARTMENT.EMP_NUM = LGEMPLOYEE.EMP_NUM
ORDER BY DEPT_NAME

--60)
SELECT	LGVENDOR.VEND_ID, VEND_NAME, BRAND_NAME, COUNT(PROD_DESCRIPT) AS [NUMPRODUCTS]
FROM	LGVENDOR, LGBRAND, LGPRODUCT, LGSUPPLIES
WHERE	LGSUPPLIES.VEND_ID = LGVENDOR.VEND_ID
		AND LGSUPPLIES.PROD_SKU = LGPRODUCT.PROD_SKU
		AND LGPRODUCT.BRAND_ID = LGBRAND.BRAND_ID
GROUP BY LGVENDOR.VEND_ID, VEND_NAME, BRAND_NAME
ORDER BY VEND_NAME, BRAND_NAME

--61)
SELECT	LGEMPLOYEE.EMP_NUM, EMP_LNAME, EMP_FNAME, SUM(INV_TOTAL) AS [TOTALINVOICES]
FROM	LGEMPLOYEE, LGINVOICE
WHERE	EMPLOYEE_ID = EMP_NUM
GROUP BY LGEMPLOYEE.EMP_NUM, EMP_LNAME, EMP_FNAME
ORDER BY EMP_LNAME, EMP_FNAME

--62
SELECT BRAND_ID, AVG(PROD_PRICE)
FROM	LGPRODUCT
GROUP BY BRAND_ID

		